In [7]:
weights = [0.1, 0.2, 0.3]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

def neural_network(inputs, weights):
    prediction = w_sum(inputs, weights)
    return prediction


In [8]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
pred

0.9800000000000001

In [2]:
import numpy as np

weights = np.array([0.1, 0.2, 0])
def neural_network(inputs, weights):
    prediction = inputs.dot(weights)
    return prediction

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
                 
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
pred

0.9800000000000001

In [6]:
a = np.array([0,1,2,3])
b = np.array([4, 5, 6, 7])
c = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])
d = np.zeros((2,4))
e = np.random.rand(2,5)

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.50145592 0.51799579 0.07613141 0.95418955 0.68242355]
 [0.55065504 0.1340035  0.71214021 0.50433473 0.48189698]]


In [14]:
print(a * 0.1)
print(a * b )
print(a * b * 0.5)
print(a * c)

[0.  0.1 0.2 0.3]
[ 0  5 12 21]
[ 0.   2.5  6.  10.5]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [18]:
a = np.zeros((1,4))
b = np.zeros((4,3))
a, b

(array([[0., 0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [21]:
c = a.dot(b)
c.shape

(1, 3)

In [58]:
knob_weight = 0.5
input = 0.5
goal_pred = 0.8

pred = input * knob_weight
error = (pred - goal_pred) ** 2
error

0.03802499999999998

In [65]:
knob_weight = 0.8
input = 0.5
goal_pred = 1
error = 1


while error > 0.0001:
    pred = (input * knob_weight)
    error = (pred - goal_pred) ** 2
    knob_weight += error

    print(pred, error)

print(f"knob_weight {knob_weight}")

0.4 0.36
0.5800000000000001 0.17639999999999995
0.6682 0.11009123999999999
0.72324562 0.07659298684918438
0.7615421134245922 0.05686216367001004
0.7899731952595972 0.04411125870946329
0.8120288246143288 0.035333162775870765
0.8296954060022642 0.029003654736733626
0.844197233370631 0.024274502089365612
0.8563344844153138 0.020639780368213716
0.8666543745994206 0.017781055813471638
0.8755449025061565 0.0154890712922021
0.8832894381522575 0.013621355246815734
0.8901001157756653 0.012077984552522176
0.8961391080519263 0.010787084876249438
0.901532650490051 0.009695818919514444
0.9063805599498083 0.008764599555311444
0.910762859727464 0.007963267204020274
0.914744493329474 0.007268501417648094
0.9183787440382981 0.006662029424765656
0.921709758750681 0.006129361874876578
0.9247744396881192 0.005658884924236411
0.9276038821502375 0.0052411978797167035
0.9302244810900958 0.004868623039146397
0.932658792609669 0.004534838212787571
0.9349262117160628 0.004234597921622679
0.9370435106768742 0.00

In [82]:
weight = 0.12

lr = 0.01

def neural_network(inputs, weights):
    prediction = inputs * weights
    return prediction

number_of_toes = [8.5]
win_or_lose_binary = [1]
input = number_of_toes[0]
true = win_or_lose_binary[0]

pred = neural_network(input, weight)

error = (pred - true) ** 2
print(error)

p_up = neural_network(input, weight) + lr
p_dn = neural_network(input, weight) - lr

e_up = (p_up - true) ** 2
e_dn = (p_dn - true) ** 2
print(f"e_up {e_up}, e_dn {e_dn}")



0.0004000000000000007
e_up 0.0009000000000000016, e_dn 0.00010000000000000018


In [97]:
from math import sqrt

weight = 0.5
input = 0.5
goal_prediction = 0.8

step_amount = 0.2

for i in range(1201):
    prediction = weight * input
    error = (prediction - goal_prediction) ** 2
    print(f"Error: {error}, prediction: {prediction}")
    
    up_prediction = input * (weight + step_amount)
    up_error = error = (up_prediction - goal_prediction) ** 2
    
    down_prediction = input * (weight - step_amount)
    down_error = error = (down_prediction - goal_prediction) ** 2
    
    if (down_error < up_error):
        weight -= step_amount
    
    if (up_error < down_error):
        weight += step_amount

Error: 0.30250000000000005, prediction: 0.25
Error: 0.20250000000000007, prediction: 0.35
Error: 0.12250000000000007, prediction: 0.44999999999999996
Error: 0.06250000000000006, prediction: 0.5499999999999999
Error: 0.02250000000000004, prediction: 0.6499999999999999
Error: 0.0025000000000000157, prediction: 0.7499999999999999
Error: 0.0024999999999999823, prediction: 0.8499999999999999
Error: 0.0025000000000000157, prediction: 0.7499999999999999
Error: 0.0024999999999999823, prediction: 0.8499999999999999
Error: 0.0025000000000000157, prediction: 0.7499999999999999
Error: 0.0024999999999999823, prediction: 0.8499999999999999
Error: 0.0025000000000000157, prediction: 0.7499999999999999
Error: 0.0024999999999999823, prediction: 0.8499999999999999
Error: 0.0025000000000000157, prediction: 0.7499999999999999
Error: 0.0024999999999999823, prediction: 0.8499999999999999
Error: 0.0025000000000000157, prediction: 0.7499999999999999
Error: 0.0024999999999999823, prediction: 0.8499999999999999


In [106]:
weight = 0.5
input = 0.5
goal_pred = 0.8


for i in range(1201):
    pred = weight * input
    error = (pred - goal_pred) ** 2
    direction_and_amount = (pred - goal_pred) * input
    weight -= direction_and_amount
    
    print(f"Error: {error},\tprediction: {pred},\tclear_err {(pred - goal_pred)},\tdaa {direction_and_amount}")
        

Error: 0.30250000000000005,	prediction: 0.25,	clear_err -0.55,	daa -0.275
Error: 0.17015625000000004,	prediction: 0.3875,	clear_err -0.41250000000000003,	daa -0.20625000000000002
Error: 0.095712890625,	prediction: 0.49062500000000003,	clear_err -0.309375,	daa -0.1546875
Error: 0.05383850097656251,	prediction: 0.56796875,	clear_err -0.23203125000000002,	daa -0.11601562500000001
Error: 0.03028415679931642,	prediction: 0.6259765625,	clear_err -0.17402343750000004,	daa -0.08701171875000002
Error: 0.0170348381996155,	prediction: 0.669482421875,	clear_err -0.1305175781250001,	daa -0.06525878906250004
Error: 0.00958209648728372,	prediction: 0.70211181640625,	clear_err -0.09788818359375007,	daa -0.04894409179687503
Error: 0.005389929274097089,	prediction: 0.7265838623046875,	clear_err -0.07341613769531252,	daa -0.03670806884765626
Error: 0.0030318352166796153,	prediction: 0.7449378967285156,	clear_err -0.05506210327148442,	daa -0.02753105163574221
Error: 0.0017054073093822882,	prediction: 0.75

In [11]:
weight = 1.6
input = 0.5
goal_pred = 0.8

alpha = 1.1

for i in range(1):
    pred = weight * input
    error = (pred - goal_pred) ** 2
    delta = (pred - goal_pred)
    weight_delta = input * delta
    weight -= weight_delta * alpha
    
    print(f"Error: {error},\tprediction: {pred},\tclear_err {(pred - goal_pred)},\tweight_delta {weight_delta}")

Error: 0.0,	prediction: 0.8,	clear_err 0.0,	weight_delta 0.0
